### ISSUE TITLE
When the code of pytorch version will be uploaded?

### ISSUE THREAD

**Issue by duanyongli** [fangchangma/sparse-to-dense.pytorch#1]
Thanks for your efforts in pytorch version. I would like to know when the pytorch version will be almost finished?

**Comment by fangchangma** [comment]
I already finished the codes but won't have much time to do testing before mid-March. Hopefully this can be released by end of March.

**Comment by maaft** [comment]
Any possibility to help with testing? Can't wait to see the pytorch implementation! :-)

**Comment by fangchangma** [comment]
> Any possibility to help with testing? Can't wait to see the pytorch implementation! :-)

Thanks for offering to help. I'll do my best to release it asap. :P

**Comment by fangchangma** [comment]
Just uploaded the codes.
