### ISSUE TITLE
Question about input image resize

### ISSUE THREAD

**Issue by ziqi-zhang** [fangchangma/sparse-to-dense.pytorch#12]
Hi, I have a question about image resize in train_transform of nyu_dataloader. It is at line 60 of nyu_dataloader.py. I wonder how can resize operation speed up rotation?

**Comment by ziqi-zhang** [comment]
And I think for kitti dataset I don't need to resize to 240?

**Comment by fangchangma** [comment]
If I recall correctly, rotation is a more expensive operation than resizing and is size-dependent. It becomes a computational bottleneck when applied directly on the KITTI images.

Any image size > 224-by-224 should work.

**Comment by ziqi-zhang** [comment]
But in torch implementation there is no resize operation. You only crop bottom of the picture. I think your point is that if I resize the bottom of kitti picture to a square picture, rotation operation will be accelerated. Is that true?

**Comment by fangchangma** [comment]
The resizing operation doesn't change the image aspect ratio but accelerates the overall speed indeed. This resizing is by no means necessary, and feel free to remove it if it is a concern to you (make sure to change the second resizing accordingly).

**Comment by whubaichuan** [comment]
@ziqi-zhang @AbigailFernandes Hi, the download speed (13kb/s ) is too low when I use the command "wget http://datasets.lids.mit.edu/sparse-to-dense/data/nyudepthv2.tar.gz" even in VPN mode. How can I raise the download speed? Looking forward to your reply.
