### ISSUE TITLE
Question about decoder

### ISSUE THREAD

**Issue by ziqi-zhang** [fangchangma/sparse-to-dense.pytorch#13]
Hi,
You said only deconv operation is implemented in decoder, but in model.py there are implementations of upproj and upconv. Is there anything wrong with upproj and upconv? Or you simply mean they are not recommended

**Comment by fangchangma** [comment]
Implementations of `upproj` and `upconv` were added later, and I forgot to update the README file accordingly. In general, `upproj` and `upconv` provide slight accuracy improvement at the cost of higher computational time.
