### ISSUE TITLE
Getting benchmark results

### ISSUE THREAD

**Issue by ShreyasSkandan** [fangchangma/sparse-to-dense.pytorch#18]
Hi,

Thank you for publicly releasing this code. I was wondering what parameters to use to arrive at the same/similar results as those in your paper / KITTI depth completion benchmark.

Should I be using the default parameters?

Best regards,
Shreyas

**Comment by fangchangma** [comment]
Hi Shreyas,

The KITTI depth completion result is from a [follow-up paper](https://arxiv.org/pdf/1807.00275.pdf), and the code will be released later in [another repo](https://github.com/fangchangma/self-supervised-depth-completion). For clarity, the "KITTI" dataset used in this repo is actually the KITTI odometry dataset, not the KITTI depth dataset (which had not been released when we started out this project).

**Comment by fangchangma** [comment]
Short answer: yes.

Longer answer: The results in the paper were generated using the Torch implementation, and I haven't done a detailed benchmarking for this pytorch code yet. However, I believe they should be pretty well in line with each other (maybe with some minor differences in accuracy).

**Comment by ShreyasSkandan** [comment]
Great, thanks for the information. I appreciate the quick responses!

Good luck on publishing your follow up work.
