### ISSUE TITLE
Share the trained model ?

### ISSUE THREAD

**Issue by Hansry** [fangchangma/sparse-to-dense.pytorch#21]
Hi, thanks for the outstanding works. I wonder if you can share the trained model based on NYU2 because the results I ran out ｉn Pytorch are different from the paper. More specifically, Ｉ defined the following parameters: samples=200, modality=rgbd, resnet50, decoder=upproj, criterion=l1, lr=0.01, then I got the following results: RMSE=0.244, Delta1=0.967, REL=0.049, which are different from the paper. I would appreciate it if you could reply me. Thank you.

**Comment by adamwolff2** [comment]
I am also very interested in getting you trained model.
Thanks

**Comment by fangchangma** [comment]
> samples=200, modality=rgbd, resnet50, decoder=upproj, criterion=l1, lr=0.01

Hi. The result you got was actually not too far away from the paper. My trained model achieved rmse=0.237 delta1=0.970 rel=0.048, and is available [here](http://datasets.lids.mit.edu/sparse-to-dense.pytorch/results/). The small gap between this result and the paper could be attributed to minor differences in platform and implementation.

**Comment by Hansry** [comment]
Thanks for your reply, which is very useful for me. Thank you very much.

**Comment by Hansry** [comment]
> > samples=200, modality=rgbd, resnet50, decoder=upproj, criterion=l1, lr=0.01
> 
> Hi. The result you got was actually not too far away from the paper. My trained model achieved rmse=0.237 delta1=0.970 rel=0.048, and is available [here](http://datasets.lids.mit.edu/sparse-to-dense.pytorch/results/). The small gap between this result and the paper could be attributed to minor differences in platform and implementation.
Thanks for your reply, which is very useful for me. Thank you very much.

**Comment by RCConnolly** [comment]
Hi @fangchangma, I am unable to extract the pre-trained model .tar files you provided. I've tried using the default file managers for both Mac OS and Ubuntu 14.04. Any suggestions on what may be causing the issue?

**Comment by fangchangma** [comment]
> I am unable to extract the pre-trained model .tar files you provided

It is pytorch's convention to store checkpoints using the `.tar` file extension. There is no need for de-compression and those files can be loaded directly in pytorch.

**Comment by tonysy** [comment]
The checkpoint website: http://datasets.lids.mit.edu/sparse-to-dense.pytorch/results/ is 404, please fix it and thanks a lot.

**Comment by fangchangma** [comment]
> The checkpoint website: http://datasets.lids.mit.edu/sparse-to-dense.pytorch/results/ is 404

Thanks for reporting the problem. We are working on it and will let you know once it has been resolved.

**Comment by fangchangma** [comment]
@tonysy The server seems to work now. Please check again.

**Comment by tonysy** [comment]
Sorry, still not work.

**Comment by fangchangma** [comment]
@tonysy There was a permission issue. Should be fine now.
