### ISSUE TITLE
CUDA sync? 

### ISSUE THREAD

**Issue by sukjaehan** [fangchangma/sparse-to-dense.pytorch#22]
Thank you so much for the great work! 

This might be a stupid question but I am getting the following error 'runtimeerror: attempting ti deserialize object on a CUDA device but torch.cuda.is_availble() is false.' This is my first time dealing with Pytorch so I guess my question is how do you run the code or make it recognize CUDA (that I downloaded) to get rid of that error? Am I making sense? 

Many thanks

**Comment by fangchangma** [comment]
This is a problem related to the installation and setup of PyTorch and CUDA, rather than the code itself. There are tutorials online regarding this, but a good start would be to run `nvidia-smi` from command line and see if you get proper response.
