### ISSUE TITLE
A issue with the arguments

### ISSUE THREAD

**Issue by abdo-eldesokey** [fangchangma/sparse-to-dense.pytorch#23]
Hi,
I just noticed that there is a conflict between the two arguments "Data" and "Decoder" as both of them are treated by default as -d.
This causes and error message when running main.py
Thank you.

**Comment by abdo-eldesokey** [comment]
I used the command in the Readme file and it complained that "ata" is not a valid value for argument --decoder/-d. So simply the parser thinks that -data is -d.

**Comment by fangchangma** [comment]
There was a typo in the README and it is now fixed. As mentioned earlier, the correct option should be `--data` (i.e., a long option with double-dash).
