### ISSUE TITLE
An issue with "resume" mode

### ISSUE THREAD

**Issue by abdo-eldesokey** [fangchangma/sparse-to-dense.pytorch#24]
Hi,
When I call --resume mode, I get an error from line 109 in main.py.
I checked an found that when you load the checkpoint, you overwrite args in line 104, which will remove the path to the checkpoint that is needed for line 109.
I suggest that you save the path in an intermediate variable.
Thank you.

**Comment by fangchangma** [comment]
Thanks and that's a bug indeed. Feel free to make a pull request and I'm happy to merge it.

**Comment by abdo-eldesokey** [comment]
A pull request was created
