### ISSUE TITLE
Is there an easy way to run inference on a different dataset

### ISSUE THREAD

**Issue by AbigailFernandes** [fangchangma/sparse-to-dense.pytorch#29]
Currently the supported method to do inference is via the --evaluate option. However, in using this, the data loaders are written to process HDF5 formats. I want to run inference on the KITTI depth completion benchmark dataset. I have the sparse depth, ground truth depth and rgb images. However, doing so will require modifying the kitti_dataloader. Is there an easy straightforward way of doing this? Thank you

**Comment by fangchangma** [comment]
Hi. In our follow-up project, we extended our code to use the KITTI Depth Dataset. Please refer to my other repo [here](https://github.com/fangchangma/self-supervised-depth-completion/blob/master/dataloaders/kitti_loader.py).

**Comment by whubaichuan** [comment]
@AbigailFernandes Hi, the download speed (13kb/s ) is too low when I use the command "wget http://datasets.lids.mit.edu/sparse-to-dense/data/nyudepthv2.tar.gz" even in VPN mode. How can I raise the download speed? Looking forward to your reply.
