### ISSUE TITLE
Apply the pretrained model to other datasets

### ISSUE THREAD

**Issue by dlfksj** [fangchangma/sparse-to-dense.pytorch#30]
Hi, I'm new to deep learning and 
I'd like to know can I apply a model trained on NYUv2 dataset to others, such as KITTI dataset.
Is it work?

**Comment by fangchangma** [comment]
> I'd like to know can I apply a model trained on NYUv2 dataset to others, such as KITTI dataset

We have a model pretrained on the KITTI Odometry dataset (not KITTI Depth). It might work ok (but probably not state-of-the-art) on KITTI Depth. However, the model trained on NYU is unlikely to work well for KITTI, since one is indoor and the other one is outdoor.

**Comment by dlfksj** [comment]
Okay. Thank you so much for your reply!
