### ISSUE TITLE
No rgb image normalization during pre-process

### ISSUE THREAD

**Issue by Ellinier** [fangchangma/sparse-to-dense.pytorch#31]
Are rgb images normalized before input into the model for training? I don't find it and it seem that rgb images are only divided by 255 and transformed to tensor. If not, why depth estimation task doesn't need the normalization process, subtract the mean and then divide by the standard deviation, which is a routine process for other CV tasks such as semantic segmentation and object detection?

**Comment by fangchangma** [comment]
In our past experiments, the normalization of sparse depth does not make a significant difference in the results, and thus we didn't keep it.
