### ISSUE TITLE
GPU Usage

### ISSUE THREAD

**Issue by timethy** [fangchangma/sparse-to-dense.pytorch#4]
Dear Ma Fang Cheng,
Thanks for your work, it's great!

I noticed that the GPU usage is far from 100% on my machine and I was curious as to how difficult you think it is to pipeline the reading and pre-processing of the training data with running the GPU.

I.e. while the GPU is running on a batch, the CPU can already begin reading in the next batch.
Since I have a rather slow CPU I think this could help quite a bit.

What do you think?

Best,
Tim

**Comment by fangchangma** [comment]
The reading and pre-loading of training data is already implemented in the code (which is quite a standard thing to do and I'll be surprised if any one is not doing this). The GPU utilization is rather high on my side, and the training should take roughly 6-9 hours, if I remember correctly. 

If you don't have a fast SSD, you can try to reduce the amount of data augmentation in the code to speed things up.

**Comment by timethy** [comment]
Ok, thanks for the tips!

I'll close this for now :)
