### ISSUE TITLE
Data generation script

### ISSUE THREAD

**Issue by calmevtime** [fangchangma/sparse-to-dense.pytorch#5]
Dear Ma Fang Cheng,
Thanks for your great work!

Can you please share the HDF5 file generation script? Thanks.

Best.

**Comment by fangchangma** [comment]
> I have a problem when i input "python3 main.py -a resnet50 -d deconv3 -m rgbd -s 100 -data nyudepthv2“
> the result as follows:

The correct command should be `python3 main.py -a resnet50 -d deconv3 -m rgbd -s 100 --data nyudepthv2`.

PS: please create a separate issue for your questions in the future.

**Comment by boni-hu** [comment]
Many thanks for  your answer,i already have an result of the project.Finally i will creat a separate issue in the future.
