### ISSUE TITLE
Saving the upproj model fails

### ISSUE THREAD

**Issue by 4bitadder** [fangchangma/sparse-to-dense.pytorch#8]
Hi 

I have a problem when training using the upproj layer. What I do is 

python main.py -a resnet50 -d upproj -m rgb

At the beginning, everything goes well, and the model can also be transferred to GPU. But it always reports error when trying to save the torch model (after validation of epoch 0, I can see the REL/RMSE of the validation)

Traceback (most recent call last):
  File "main.py", line 393, in <module>
    main()
  File "main.py", line 236, in main
    }, is_best, epoch)
  File "main.py", line 377, in save_checkpoint
    torch.save(state, checkpoint_filename)
  File "/cm/shared/apps/pytorch/0.1.12/lib64/python2.7/site-packages/torch/serialization.py", line 120, in save
    return _save(obj, f, pickle_module, pickle_protocol)
  File "/cm/shared/apps/pytorch/0.1.12/lib64/python2.7/site-packages/torch/serialization.py", line 186, in _save
    pickler.dump(obj)
cPickle.PicklingError: Can't pickle <class 'models.UpProjModule'>: attribute lookup models.UpProjModule failed

But if I use deconv3, everything works well.

Could you help me with this issue? Thanks a lot.

**Comment by 4bitadder** [comment]
Hi

I tried in CentOS, Pytorch 0.1.12, and python 2.7.

Since this old version does not have the 'nn.Upsample' layer, I use 'nn.UpsamplingBilinear2d' instead. It works for training with deconv, e.g.,

python main.py -a resnet50 -d deconv3 -m rgbd

**Comment by fangchangma** [comment]
Unfortunately, it is very hard to maintain backward compatibility for PyTorch 0.1.x. Could you try upgrading your PyTorch to at least 0.3.1 and see if the problem remains?

**Comment by 4bitadder** [comment]
Thanks. After swithing to Python 3.5 and Pytorch 0.4.0, the saving procedure works fine.

But I have to disable the saving csv part in main.py, sometimes the code crashed after writing csv several times (e.g., around epoch 7-10). Not clear for the reason.

**Comment by fangchangma** [comment]
Do you mind sharing the error messages?
